# Generated by Django 3.0.8 on 2020-07-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200724_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='category',
            name='cat',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
