# Generated by Django 3.0.8 on 2020-07-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
