# Generated by Django 3.0.8 on 2020-07-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='max_bet',
            field=models.FloatField(default=0),
        ),
    ]
