# Generated by Django 3.0.8 on 2020-07-26 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200725_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='win',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='win', to=settings.AUTH_USER_MODEL),
        ),
    ]
